version: '2'
services:
    aakaelmo-app:
        image: aakaelmo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aakaelmo-mysql:3306/aakaelmo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aakaelmo-mysql:
        extends:
            file: mysql.yml
            service: aakaelmo-mysql
